#!/usr/bin/env -S python3 -SI

import argparse
import asyncio
import shlex
import sys
import os
import socket
import subprocess
from functools import partial
from pathlib import Path

LOCALHOST = '127.0.0.1'

def get_free_port():
    with socket.socket() as s:
        s.bind(("", 0))
        return s.getsockname()[1]

def create_task(fut):
    task = asyncio.create_task(fut)
    task.add_done_callback(lambda x: x.cancelled() or x.result())
    return task

async def tcp_forward_streams(reader, writer, size=4096):
    while True:
        buf = await reader.read(4096)
        if not buf:
            writer.close()
            await writer.wait_closed()
            return
        await writer.drain()
        writer.write(buf)

async def tcp_forward_client(to_addr, start_mitmproxy, src_reader, src_writer):
    await start_mitmproxy()
    dst_reader, dst_writer = await asyncio.open_connection(*to_addr)
    async with asyncio.TaskGroup() as tasks:
        forward = tasks.create_task(tcp_forward_streams(src_reader, dst_writer))
        backward = tasks.create_task(tcp_forward_streams(dst_reader, src_writer))

async def tcp_forward_server(from_addr, to_addr, start_mitmproxy):
    server = await asyncio.start_server(partial(tcp_forward_client, to_addr, start_mitmproxy), *from_addr)
    async with server:
        await server.serve_forever()

class UdpClient(asyncio.DatagramProtocol):
    def __init__(self, queue=None, addr=None):
        self.queue = queue or asyncio.Queue()
        self.addr = addr
        self.activity_counter = 0
        self.active = True

    def datagram_received(self, data, addr):
        if self.active:
            self.queue.put_nowait((self, data, addr))

async def udp_forward_server(from_addr, to_addr, start_mitmproxy):
    loop = asyncio.get_running_loop()
    transport, server = await loop.create_datagram_endpoint(UdpClient, local_addr=from_addr)
    proxies = {}
    gc_task = create_task(udp_gc_clients(proxies))
    while True:
        client, data, addr = await server.queue.get()
        if client is server:
            if addr not in proxies:
                # make a new conn to mitmproxy
                await start_mitmproxy()
                proxies[addr] = await loop.create_datagram_endpoint(partial(UdpClient, server.queue, addr), remote_addr=to_addr)
            proxies[addr][1].activity_counter += 1
            proxies[addr][0].sendto(data, to_addr)
        elif client.active:
            # forward back to the client
            client.activity_counter += 1
            transport.sendto(data, client.addr)

async def udp_gc_clients(proxies, interval=20):
    # mitmproxy has a udp timeout of 20s
    counters = {}
    while True:
        await asyncio.sleep(interval)
        for addr in counters.keys() | proxies.keys():
            if addr not in proxies:
                counters.pop(addr)
            elif counters.get(addr) == proxies[addr][1].activity_counter:
                # counter hasn't changed, assume inactivity
                transport, client = proxies.pop(addr)
                client.active = False
                transport.close()
            else:
                counters[addr] = proxies[addr][1].activity_counter

class Handler:
    def __init__(self, args, extras, lazy=True):
        self.args = args
        self.extras = extras
        self.mitm = None
        self.lazy = lazy

        self.dns_port = get_free_port()
        self.wg_port = get_free_port()

        self.tap_iface = 'eth0'
        self.wg_iface = 'eth1'
        self.tap_subnet = '169.254.2.1/32'
        self.host_ip = '192.168.1.2'
        self.wg_ip = '192.168.2.2'
        self.wg_subnet = f'{self.wg_ip}/24'
        self.wg_conf = Path('~/.mitmproxy/wireguard.conf').expanduser()

    async def run_pasta(self):
        command = ' '.join(map(shlex.quote, self.extras))
        python = shlex.quote(sys.executable)
        wg_conf = shlex.quote(str(self.wg_conf))

        script_sh = f'''
set -eu -o pipefail
# bc you may have no jq
extract_json() {{ {python} -c 'import sys, json; print(json.load(sys.stdin)[sys.argv[1]])' "$@"; }}
# set up wireguard
ip link add dev {self.wg_iface} type wireguard
ip address add dev {self.wg_iface} {self.wg_subnet}
wg set {self.wg_iface} private-key <(<{wg_conf} extract_json client_key) peer "$(<{wg_conf} extract_json server_key | wg pubkey)" allowed-ips 0.0.0.0/0 endpoint {self.host_ip}:{self.wg_port}
ip link set up dev {self.wg_iface}

# route everything through wireguard
ip route show | grep -F 'dev {self.tap_iface}' | cut -d' ' -f1 | xargs -n1 ip route del
ip route add default via {self.wg_ip} dev {self.wg_iface}
ip route add {self.host_ip}/32 dev {self.tap_iface}
# drop everything else
iptables -A OUTPUT -p udp -d {self.host_ip} --dport {self.wg_port} -o {self.tap_iface} -j ACCEPT
for cmd in iptables ip6tables; do
    "$cmd" -A OUTPUT -o {self.tap_iface} -j DROP
    "$cmd" -A OUTPUT -p udp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -p tcp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -o {self.wg_iface} -j DROP
done

mount -t tmpfs -o size=10M tmpfs /tmp
# override some files
echo nameserver {LOCALHOST} > /tmp/resolv.conf
cat /etc/ssl/certs/ca-certificates.crt ~/.mitmproxy/mitmproxy-ca-cert.pem > /tmp/certs
mount --bind /tmp/resolv.conf /etc/resolv.conf -o ro
mount --bind /tmp/certs /etc/ssl/certs/ca-certificates.crt -o ro
umount /tmp

# drop net admin and reset user
setpriv --inh-caps -net_admin --bounding-set -net_admin --pdeathsig SIGKILL \\
unshare --map-user {os.geteuid()} --map-group {os.getegid()} -- \\
{command}
'''

        # technically i could just run the command directly inside pasta
        # if we are already inside bwrap (bwrap -> pasta -> setpriv -> unshare -> command) it doesn't seem to work
        # instead if we do (bwrap -> pasta -> CHILD) and (bwrap -> nsenter CHILD -> setpriv -> unshare -> command)
        # this seems to work

        pasta = await asyncio.create_subprocess_exec(
            'pasta',
            '--ipv4-only',
            '--address', self.tap_subnet.partition('/')[0],
            '--netmask', self.tap_subnet.partition('/')[2],
            '-T', f'53:{self.dns_port}',
            '-U', f'53:{self.dns_port}',
            #  '-t', 'auto',
            #  '-u', 'auto',
            '-I', self.tap_iface,
            '--map-host-loopback', self.host_ip,
            '--config-net',
            '--',
            'setpriv', '--pdeathsig', 'SIGKILL',
            'sh', '-c', 'echo 123 && sleep inf',
            stdout=subprocess.PIPE,
            env={k: v for k, v in os.environ.items() if k not in {'LD_PRELOAD'}},
        )
        await pasta.stdout.readline()

        # there should only be one
        child_pid = Path(f'/proc/{pasta.pid}/task/{pasta.pid}/children').read_text().split()[0]
        nsenter = await asyncio.create_subprocess_exec(
            'nsenter',
            '--net', '--pid', '--mount', '--user',
            '--wd=' + os.getcwd(),
            '--keep-caps',
            '--preserve-credentials',
            '--target', child_pid,
            '--',
            'bash', '-c', script_sh,
        )

        try:
            return await nsenter.wait()
        finally:
            if nsenter.returncode is None:
                nsenter.terminate()
            if pasta.returncode is None:
                pasta.terminate()

    async def _start_mitmproxy(self):
        # use this pipe to signal readiness
        r, w = os.pipe()

        proc = await asyncio.create_subprocess_exec(
            'mitmdump',
            '--mode', f'wireguard@{LOCALHOST}:{self.mitm_wg_port}',
            '--mode', f'dns@{LOCALHOST}:{self.mitm_dns_port}',
            '--scripts', Path(__file__).resolve().parent/'mitm.py',
            '--show-ignored-hosts',
            '--set=connection_strategy=lazy',
            f'--set=nsb_readiness_fd={w}',
             '--showhost',
            *self.args,
            pass_fds=[w],
            start_new_session=True,
        )

        try:
            os.close(w)
            reader = asyncio.StreamReader()
            await asyncio.get_running_loop().connect_read_pipe(lambda: asyncio.StreamReaderProtocol(reader), os.fdopen(r, 'rb'))
            buf = await reader.read()
            if buf != b'1':
                raise Exception('mitmdump failed to start properly')
        except Exception:
            proc.terminate()
            raise

        return proc

    def start_mitmproxy(self):
        if self.mitm is None:
            self.mitm = create_task(self._start_mitmproxy())
        return self.mitm

    def mitmproxy_is_finished(self):
        return self.mitm and self.mitm.done() and self.mitm.result().returncode is not None

    async def main(self):
        tasks = []

        if self.wg_conf.exists() and self.lazy:
            self.mitm_dns_port = get_free_port()
            self.mitm_wg_port = get_free_port()

            tasks = [
                create_task(udp_forward_server((LOCALHOST, self.wg_port), (LOCALHOST, self.mitm_wg_port), self.start_mitmproxy)),
                create_task(udp_forward_server((LOCALHOST, self.dns_port), (LOCALHOST, self.mitm_dns_port), self.start_mitmproxy)),
                create_task(tcp_forward_server((LOCALHOST, self.dns_port), (LOCALHOST, self.mitm_dns_port), self.start_mitmproxy)),
            ]

        else:
            # launch mitmproxy first to create the wg config
            self.mitm_wg_port = self.wg_port
            self.mitm_dns_port = self.dns_port
            await self.start_mitmproxy()
            while not self.wg_conf.exists() and not self.mitmproxy_is_finished():
                await asyncio.sleep(0.1)

        try:
            return await self.run_pasta()
        finally:
            for t in tasks:
                t.cancel()

async def main():
    parser = argparse.ArgumentParser(description='Network sandbox')
    parser.add_argument('--no-lazy-mitm', action='store_true', help='start mitmdump immediately')
    parser.add_argument('command', nargs=argparse.REMAINDER, help='command to run in the sandbox')

    args, mitm_args = parser.parse_known_args()

    # strip leading '--' from command if present
    command = args.command
    if command and command[0] == '--':
        command = command[1:]

    handler = Handler(mitm_args, command, lazy=not args.no_lazy_mitm)
    return await handler.main()


if __name__ == '__main__':
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        pass
