#!/usr/bin/env -S python3 -SI

import asyncio
import shlex
import sys
import os
import socket
import subprocess
import shutil
import signal
import argparse
from functools import partial
from pathlib import Path

LOCALHOST = '127.0.0.1'

def get_free_port():
    with socket.socket() as s:
        s.bind(("", 0))
        return s.getsockname()[1]

def create_task(fut):
    task = asyncio.create_task(fut)
    task.add_done_callback(lambda x: x.cancelled() or x.result())
    return task

class UdpClient(asyncio.DatagramProtocol):
    def __init__(self, queue=None, addr=None):
        self.queue = queue or asyncio.Queue()
        self.addr = addr
        self.activity_counter = 0
        self.active = True

    def datagram_received(self, data, addr):
        if self.active:
            self.queue.put_nowait((self, data, addr))

async def udp_forward_server(from_addr, to_addr, start_mitmproxy):
    loop = asyncio.get_running_loop()
    transport, server = await loop.create_datagram_endpoint(UdpClient, local_addr=from_addr)
    proxies = {}
    gc_task = create_task(udp_gc_clients(proxies))
    while True:
        client, data, addr = await server.queue.get()
        if client is server:
            if addr not in proxies:
                # make a new conn to mitmproxy
                await start_mitmproxy()
                proxies[addr] = await loop.create_datagram_endpoint(partial(UdpClient, server.queue, addr), remote_addr=to_addr)
            proxies[addr][1].activity_counter += 1
            proxies[addr][0].sendto(data, to_addr)
        elif client.active:
            # forward back to the client
            client.activity_counter += 1
            transport.sendto(data, client.addr)

async def udp_gc_clients(proxies, interval=20):
    # mitmproxy has a udp timeout of 20s
    counters = {}
    while True:
        await asyncio.sleep(interval)
        for addr in counters.keys() | proxies.keys():
            if addr not in proxies:
                counters.pop(addr)
            elif counters.get(addr) == proxies[addr][1].activity_counter:
                # counter hasn't changed, assume inactivity
                transport, client = proxies.pop(addr)
                client.active = False
                transport.close()
            else:
                counters[addr] = proxies[addr][1].activity_counter

class Handler:
    def __init__(self, args, extras, lazy=False, tcp_ports=None, udp_ports=None, wg_port=None):
        self.args = args
        self.extras = extras
        self.mitm = None
        self.lazy = lazy
        self.tcp_ports = tcp_ports
        self.udp_ports = udp_ports
        self.wg_port = wg_port or get_free_port()

        self.mitmproxy_path = shutil.which('mitmdump')

        self.root_dir = Path(__file__).resolve().parent
        self.mitm_script = self.root_dir/'mitm.py'

        self.tap_iface = 'eth0'
        self.wg_iface = 'eth1'
        self.tap_subnet = '169.254.2.1/32'
        self.host_ip = '192.168.1.2'
        self.wg_ip = '192.168.2.2'
        self.wg_subnet = f'{self.wg_ip}/24'
        self.wg_conf = Path('~/.mitmproxy/wireguard.conf').expanduser()
        # seems to be a special ip
        self.nameserver = '10.0.0.53'

    async def run_pasta(self, wg_port):
        command = ' '.join(map(shlex.quote, self.extras))
        python = shlex.quote(sys.executable)
        wg_conf = shlex.quote(str(self.wg_conf))

        script_sh = f'''
set -eu -o pipefail
# bc you may have no jq
extract_json() {{ {python} -c 'import sys, json; print(json.load(sys.stdin)[sys.argv[1]])' "$@"; }}
# set up wireguard
ip link add dev {self.wg_iface} type wireguard
ip address add dev {self.wg_iface} {self.wg_subnet}
wg set {self.wg_iface} private-key <(<{wg_conf} extract_json client_key) peer "$(<{wg_conf} extract_json server_key | wg pubkey)" allowed-ips 0.0.0.0/0 endpoint {self.host_ip}:{wg_port}
ip link set up dev {self.wg_iface}

# route everything through wireguard
ip route show | grep -F 'dev {self.tap_iface}' | cut -d' ' -f1 | xargs -n1 ip route del
ip route add default via {self.wg_ip} dev {self.wg_iface}
ip route add {self.host_ip}/32 dev {self.tap_iface}
# drop everything else
iptables -A OUTPUT -p udp -d {self.host_ip} --dport {wg_port} -o {self.tap_iface} -j ACCEPT
for cmd in iptables ip6tables; do
    "$cmd" -A OUTPUT -o {self.tap_iface} -j DROP
    "$cmd" -A OUTPUT -p udp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -p tcp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -o {self.wg_iface} -j DROP
done

mount -t tmpfs -o size=10M tmpfs /tmp
# override some files
echo nameserver {self.nameserver} > /tmp/resolv.conf
cat /etc/ssl/certs/ca-certificates.crt ~/.mitmproxy/mitmproxy-ca-cert.pem > /tmp/certs
mount --bind /tmp/resolv.conf /etc/resolv.conf -o ro
mount --bind /tmp/certs /etc/ssl/certs/ca-certificates.crt -o ro
umount /tmp

mount --bind ~/.mitmproxy/{{,}} -o ro

cd .
# drop net admin and reset user
setpriv --inh-caps -net_admin --bounding-set -net_admin --pdeathsig SIGKILL \\
unshare --map-user {os.geteuid()} --map-group {os.getegid()} -- \\
{command}
'''

        # technically i could just run the command directly inside pasta
        # if we are already inside bwrap (bwrap -> pasta -> setpriv -> unshare -> command) it doesn't seem to work
        # instead if we do (bwrap -> pasta -> CHILD) and (bwrap -> nsenter CHILD -> setpriv -> unshare -> command)
        # this seems to work

        args = [
            'pasta',
            '--ipv4-only',
            '--address', self.tap_subnet.partition('/')[0],
            '--netmask', self.tap_subnet.partition('/')[2],
            '-T', 'none',
            '-U', 'none',
            '-t', self.tcp_ports,
            '-u', self.udp_ports,
            '-I', self.tap_iface,
            '--map-host-loopback', self.host_ip,
            '--config-net',
        ]
        pasta = await asyncio.create_subprocess_exec(
            *args,
            '--',
            'setpriv', '--pdeathsig', 'SIGKILL',
            # we add && exit so that sh stays running and reaps children
            'sh', '-c', 'echo 123 && sleep inf && exit',
            stdout=subprocess.PIPE,
            env={k: v for k, v in os.environ.items() if k not in {'LD_PRELOAD'}},
        )
        await pasta.stdout.readline()

        # there should only be one
        child_pid = int(Path(f'/proc/{pasta.pid}/task/{pasta.pid}/children').read_text().split()[0])
        nsenter = None

        try:
            nsenter = await asyncio.create_subprocess_exec(
                'nsenter',
                '--net', '--pid', '--mount', '--user',
                '--wd=' + os.getcwd(),
                '--keep-caps',
                '--preserve-credentials',
                '--target', str(child_pid),
                '--',
                'bash', '-c', script_sh,
            )
            return await nsenter.wait()
        finally:
            if nsenter and nsenter.returncode is None:
                try:
                    nsenter.terminate()
                except ProcessLookupError:
                    pass
            if pasta.returncode is None:
                try:
                    pasta.terminate()
                except ProcessLookupError:
                    pass
            try:
                # pasta may fail to kill the child due to selinux or something
                os.kill(child_pid, signal.SIGKILL)
            except ProcessLookupError:
                pass

    async def _start_mitmproxy(self, wg_port, **kwargs):
        # use this pipe to signal readiness
        r, w = os.pipe()

        kwargs.setdefault('start_new_session', True)
        proc = await asyncio.create_subprocess_exec(
            self.mitmproxy_path,
            '--mode', f'wireguard@{LOCALHOST}:{wg_port}',
            '--scripts', self.mitm_script,
            '--show-ignored-hosts',
            '--set=connection_strategy=lazy',
            f'--set=nsb_readiness_fd={w}',
             '--showhost',
            *self.args,
            pass_fds=[w],
            **kwargs,
        )

        try:
            os.close(w)
            reader = asyncio.StreamReader()
            await asyncio.get_running_loop().connect_read_pipe(lambda: asyncio.StreamReaderProtocol(reader), os.fdopen(r, 'rb'))

            read_task = asyncio.create_task(reader.read())
            wait_task = asyncio.create_task(proc.wait())
            done, pending = await asyncio.wait([read_task, wait_task], return_when=asyncio.FIRST_COMPLETED)

            if wait_task in done:
                # mitmdump exited
                read_task.cancel()
                raise Exception(f'mitmdump exited with code {proc.returncode} before becoming ready')

            wait_task.cancel()
            if read_task.result() != b'1':
                raise Exception('mitmdump failed to start properly')

        except Exception:
            proc.terminate()
            raise

        return proc

    def start_mitmproxy(self, wg_port, **kwargs):
        if self.mitm is None:
            self.mitm = create_task(self._start_mitmproxy(wg_port, **kwargs))
        return self.mitm

    def mitmproxy_is_finished(self):
        return self.mitm and self.mitm.done() and self.mitm.result().returncode is not None

    async def main(self):
        tasks = []

        if self.wg_conf.exists() and self.lazy:
            mitm_wg_port = get_free_port()
            start_mitmproxy = partial(self.start_mitmproxy, mitm_wg_port)

            tasks = [
                create_task(udp_forward_server((LOCALHOST, self.wg_port), (LOCALHOST, mitm_wg_port), start_mitmproxy)),
            ]

        else:
            # launch mitmproxy first to create the wg config
            await self.start_mitmproxy(self.wg_port)
            while not self.wg_conf.exists() and not self.mitmproxy_is_finished():
                await asyncio.sleep(0.1)

        try:
            return await self.run_pasta(self.wg_port)
        finally:
            for t in tasks:
                t.cancel()

async def main():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--lazy-mitmdump', action='store_true', help='start mitmproxy lazily')
    group.add_argument('--only-mitmdump', action='store_true', help='only start mitmdump, do not run the command')
    group.add_argument('--no-mitmdump', action='store_true', help='only run the command, do not run start mitmdump')
    parser.add_argument('--tcp-ports', default='none', help='tcp ports to forward (default: %(default)s)')
    parser.add_argument('--udp-ports', default='none', help='udp ports to forward (default: %(default)s)')
    parser.add_argument('--wg-port', type=int)
    parser.add_argument('command', nargs=argparse.REMAINDER, help='command to run')

    # argparse treats unknown args with spaces as positional even if they start with --
    args = [a.replace(' ', '\x00') if a.startswith('--') else a for a in sys.argv[1:]]

    args, mitm_args = parser.parse_known_args(args)

    mitm_args = [a.replace('\x00', ' ') for a in mitm_args]
    if args.command and args.command[0] == '--':
        args.command.pop(0)
    args.command = [a.replace('\x00', ' ') for a in args.command]
    for k, v in vars(args).items():
        if isinstance(v, str):
            setattr(args, k, v.replace('\x00', ' '))

    handler = Handler(
        mitm_args,
        args.command,
        lazy=args.lazy_mitmdump,
        tcp_ports=args.tcp_ports,
        udp_ports=args.udp_ports,
        wg_port=args.wg_port,
    )
    if args.only_mitmdump:
        proc = await handler.start_mitmproxy(handler.wg_port, start_new_session=False)
        return await proc.wait()
    elif args.no_mitmdump:
        if not args.wg_port:
            parser.error('--no-mitmdump requires --wg-port')
        return await handler.run_pasta(args.wg_port)
    else:
        return await handler.main()


if __name__ == '__main__':
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        pass
