#!/usr/bin/env -S python3 -SI

import asyncio
import shlex
import sys
import shutil
import os
import json
import socket
import subprocess
from functools import partial
from pathlib import Path

LOCALHOST = '127.0.0.1'

def get_free_port():
    with socket.socket() as s:
        s.bind(("", 0))
        return s.getsockname()[1]

def create_task(fut):
    task = asyncio.create_task(fut)
    task.add_done_callback(lambda x: x.cancelled() or x.result())
    return task

async def tcp_forward_streams(reader, writer, size=4096):
    while True:
        buf = await reader.read(4096)
        if not buf:
            writer.close()
            await writer.wait_closed()
            return
        await writer.drain()
        writer.write(buf)

async def tcp_forward_client(to_addr, start_mitmproxy, src_reader, src_writer):
    await start_mitmproxy()
    dst_reader, dst_writer = await asyncio.open_connection(*to_addr)
    async with asyncio.TaskGroup() as tasks:
        forward = tasks.create_task(tcp_forward_streams(src_reader, dst_writer))
        backward = tasks.create_task(tcp_forward_streams(dst_reader, src_writer))

async def tcp_forward_server(from_addr, to_addr, start_mitmproxy):
    server = await asyncio.start_server(partial(tcp_forward_client, to_addr, start_mitmproxy), *from_addr)
    async with server:
        await server.serve_forever()

class UdpClient:
    def __init__(self):
        self.activity_counter = 0

    def connection_made(self, transport):
        self.transport = transport

    def datagram_received(self, data, addr):
        pass

    def error_received(self, exc):
        pass

    def connection_lost(self, exc):
        pass

    def send(self, data, addr):
        self.activity_counter += 1
        self.transport.sendto(data, addr)

    def forward_to_transport(self, transport, addr, data, _addr):
        self.activity_counter += 1
        transport.sendto(data, addr)

async def udp_forward_server(from_addr, to_addr, start_mitmproxy):
    queue = asyncio.Queue()
    transport, server = await asyncio.get_running_loop().create_datagram_endpoint(UdpClient, local_addr=from_addr)
    server.datagram_received = lambda data, addr: queue.put_nowait((data, addr))
    clients = {}
    started = False
    gc_task = create_task(udp_gc_clients(clients))
    while True:
        data, addr = await queue.get()
        if not started:
            await start_mitmproxy()
            started = True
        if addr not in clients:
            _, clients[addr] = await asyncio.get_running_loop().create_datagram_endpoint(UdpClient, remote_addr=to_addr)
            clients[addr].datagram_received = partial(clients[addr].forward_to_transport, transport, addr)
        clients[addr].transport.sendto(data, to_addr)

async def udp_gc_clients(clients, interval=20):
    # mitmproxy has a udp timeout of 20s
    counters = {}
    while True:
        await asyncio.sleep(interval)
        for addr in counters.keys() | clients.keys():
            if client := clients.get(addr):
                if counters.get(addr, None) == client.activity_counter:
                    clients.pop(addr)
                else:
                    counters[addr] = client.activity_counter
            else:
                counters.pop(addr)

class Handler:
    def __init__(self, args, extras):
        self.args = args
        self.extras = extras
        self.mitm = None

        self.dns_port = get_free_port()
        self.wg_port = get_free_port()

        self.tap_iface = 'eth0'
        self.wg_iface = 'eth1'
        self.tap_subnet = '169.254.2.1/32'
        self.host_ip = '192.168.1.2'
        self.wg_ip = '192.168.2.2'
        self.wg_subnet = f'{self.wg_ip}/24'
        self.wg_conf = Path('~/.mitmproxy/wireguard.conf').expanduser()

    async def start_pasta(self):
        command = ' '.join(map(shlex.quote, self.extras))
        if ld_preload := os.environ.pop('LD_PRELOAD', None):
            command = f'/usr/bin/env LD_PRELOAD={shlex.quote(ld_preload)} {command}'

        wg_conf = json.loads(self.wg_conf.read_text())
        client_key = wg_conf['client_key']
        # i could do async but this is just easier
        server_key = subprocess.check_output(['wg', 'pubkey'], input=wg_conf['server_key'], text=True).strip('\n')
        path = subprocess.check_output(['/usr/bin/getconf', 'PATH'], text=True).strip('\n')

        script_sh = f'''
set -eu -o pipefail
# set up wireguard
ip link add dev {self.wg_iface} type wireguard
ip address add dev {self.wg_iface} {self.wg_subnet}
wg set {self.wg_iface} private-key <(printf %s "$__wg_client_key") peer "$__wg_server_key" allowed-ips 0.0.0.0/0 endpoint {self.host_ip}:{self.wg_port}
unset __wg_client_key __wg_server_key
ip link set up dev {self.wg_iface}

# route everything through wireguard
ip route show | grep -F 'dev {self.tap_iface}' | cut -d' ' -f1 | xargs -n1 ip route del
ip route add default via {self.wg_ip} dev {self.wg_iface}
ip route add {self.host_ip}/32 dev {self.tap_iface}
# drop everything else
iptables -A OUTPUT -p udp -d {self.host_ip} --dport {self.wg_port} -o {self.tap_iface} -j ACCEPT
for cmd in iptables ip6tables; do
    "$cmd" -A OUTPUT -o {self.tap_iface} -j DROP
    "$cmd" -A OUTPUT -p udp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -p tcp -o {self.wg_iface} -j ACCEPT
    "$cmd" -A OUTPUT -o {self.wg_iface} -j DROP
done

mount -t tmpfs -o size=10M tmpfs /tmp
# override some files
echo nameserver {LOCALHOST} > /tmp/resolv.conf
cat /etc/ssl/certs/ca-certificates.crt ~/.mitmproxy/mitmproxy-ca-cert.pem > /tmp/certs
[[ -e /etc ]] || mount -t tmpfs -o size=100M tmpfs /etc
mount --bind /tmp/resolv.conf /etc/resolv.conf -o ro
mount --bind /tmp/certs /etc/ssl/certs/ca-certificates.crt -o ro
umount /tmp

# drop net admin and reset user
setpriv --bounding-set -net_admin -- \\
unshare --map-user {os.geteuid()} --map-group {os.getegid()} -- \\
{command}
'''

        return await asyncio.create_subprocess_exec(
            shutil.which('pasta', path=path),
            '--ipv4-only',
            '--address', self.tap_subnet.partition('/')[0],
            '--netmask', self.tap_subnet.partition('/')[2],
            '-T', f'53:{self.dns_port}',
            '-U', f'53:{self.dns_port}',
            #  '-t', 'auto',
            #  '-u', 'auto',
            '-I', self.tap_iface,
            '--map-host-loopback', self.host_ip,
            '--config-net',
            'bash', '-c', script_sh,

            env={
                '__wg_server_key': server_key,
                '__wg_client_key': client_key,
                **{k: v for k, v in os.environ.items() if k not in {'LD_PRELOAD'}},
            }
        )

    async def _start_mitmproxy(self):
        proc = await asyncio.create_subprocess_exec(
            'mitmdump',
            '--mode', f'wireguard@{LOCALHOST}:{self.mitm_wg_port}',
            '--mode', f'dns@{LOCALHOST}:{self.mitm_dns_port}',
            '--show-ignored-hosts',
            #  '--showhost',
            *self.args,
        )

        # wait for the dns to be up
        # for udp i don't know when the server is actually up
        # which means any request we send too early will disappear
        # and will have to wait for timeout+retry
        # its faster to hold and send it only once we know its working

        # i swear this works
        query = b'\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00' + b'\x00' + b'\x00\x01\x00\x01'

        addr = (LOCALHOST, self.mitm_dns_port)
        queue = asyncio.Queue()
        _, client = await asyncio.get_running_loop().create_datagram_endpoint(UdpClient, remote_addr=addr)
        client.datagram_received = lambda data, addr: queue.put_nowait((data, addr))
        while True:
            client.transport.sendto(query, addr)
            try:
                await asyncio.wait_for(queue.get(), timeout=0.1)
                break
            except TimeoutError:
                pass

        return proc

    def start_mitmproxy(self):
        if self.mitm is None:
            self.mitm = create_task(self._start_mitmproxy())
        return self.mitm

    def mitmproxy_is_finished(self):
        return self.mitm and self.mitm.done() and self.mitm.result().returncode is not None

    async def main(self):
        tasks = []

        if self.wg_conf.exists():
            pasta = await self.start_pasta()

            self.mitm_dns_port = get_free_port()
            self.mitm_wg_port = get_free_port()

            tasks = [
                create_task(udp_forward_server((LOCALHOST, self.wg_port), (LOCALHOST, self.mitm_wg_port), self.start_mitmproxy)),
                create_task(udp_forward_server((LOCALHOST, self.dns_port), (LOCALHOST, self.mitm_dns_port), self.start_mitmproxy)),
                create_task(tcp_forward_server((LOCALHOST, self.dns_port), (LOCALHOST, self.mitm_dns_port), self.start_mitmproxy)),
            ]

        else:
            # launch mitmproxy first to create the wg config
            self.mitm_wg_port = self.wg_port
            self.mitm_dns_port = self.dns_port
            await self.start_mitmproxy()
            while not self.wg_conf.exists() and not self.mitmproxy_is_finished():
                await asyncio.sleep(0.1)

            pasta = await self.start_pasta()

        rc = await pasta.wait()
        for t in tasks:
            t.cancel()
        return rc

async def main():
    args = []
    extras = None
    for arg in sys.argv[1:]:
        if extras is not None:
            extras.append(arg)
        elif arg == '--':
            extras = []
        elif not arg.startswith('--'):
            extras = [arg]
        else:
            args.append(arg)

    return await Handler(args, extras).main()


if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
